// Generated by dts-bundle v0.4.3

declare module 'MdrMetadatSwagger' {
    export var OdataTools: {
        metadata: (model: any, nameSpace: string) => any;
        docSwagger: (models: any, nameSpace: string, req: any) => any;
    };
}

